ecma_builtin_helper_string_find_index separated into two parts: ecma_…
jerryscript-project/jerryscript pull request #3978
Opened 2020-07-06 07:26 UTC by orkvi

2020-07-06 08:09 UTC, rerobika commented on tests/jerry/regression-test-issue-3903.js
> +    print(a);
That should have been an assert.

2020-07-06 08:12 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
>  bool
I suggest to use the return value as uint32_t with the matching index and `UIN32T_MAX` for not matching.

2020-07-06 09:23 UTC, galpeter commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> + * NaN is mapped to zero or length depending on the nan_to_zero parameter.
This comment seems to be outdated (is there a "nan_to_zero" paramter?)

2020-07-06 09:24 UTC, galpeter commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +static ecma_value_t
Based on the comment above this should return "uint32_t" and not "ecma_value_t" which one is the correct one?

2020-07-06 09:25 UTC, galpeter commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +                                            ecma_value_t position) /**<start_position  */
Missing space after the `<` symbol.

2020-07-06 09:28 UTC, galpeter commented on tests/jerry/regression-test-issue-3903.js
> +var NISLFuzzingFunc = function(){
Missing copyright and licence comment block.

2020-07-10 13:46 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +
Please rever this change.

2020-07-10 13:48 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +  if (mode == ECMA_STRING_LAST_INDEX_OF)
Could this block be moved into the switch below?

2020-07-10 13:49 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +      if (ecma_builtin_helper_string_find_index (original_str_p, search_str_p,
I think it would make more sense to use `ecma_builtin_helper_string_find_last_index` for `ECMA_STRING_ENDS_WITH`.

2020-07-10 13:50 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +    lit_utf8_incr (&start_p);
Would it make sense to start from the end of the string and use` lit_utf8_decr`?

2020-07-10 13:52 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +    if ((size_t) (original_end_p - str_current_p) < search_str_size)
Could this be negated and moved into the `while` condition?

2020-07-10 13:53 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +    *ret_index_p = start_pos;
`ret_index_p` no longer seems to be necessary, the returned valus has the same information.

2020-07-10 13:56 UTC, dbatyai commented
Please also add a proper short description for the commit, the current one is way too long. Something like `Separate ecma_builtin_helper_string_find_index into two parts` would do.

2020-07-21 11:13 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +    return ecma_make_uint32_value (start);
At this point the string buffers will leak. The two `ECMA_STRING_TO_UTF8_STRING` calls should be moved below this block.

2020-07-21 11:13 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +                                                      (uint32_t) start_ends_with) != UINT32_MAX)
Each argument should be in a separate line.

2020-07-21 11:14 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +                                             (ecma_builtin_helper_string_find_index (original_str_p, search_str_p,
This shouldn't be called twice, you could store the result of the first call in a variable and reuse it.

2020-07-21 11:15 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +        ret_num = ((ecma_number_t) ecma_builtin_helper_string_find_index (original_str_p, search_str_p, start));
Same here, shouldn't call twice.

2020-07-27 17:01 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +      if (ecma_builtin_helper_string_find_index (original_str_p, search_str_p, start) != UINT32_MAX)
Shouldn't be called twice.

2020-07-27 17:02 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +      if (index != UINT32_MAX)
I don't think this check is necessary, you could do
```
ecma_value_t index = ecma_builtin_helper_string_find_index (...)
ret_value = ecma_make_boolean_value (index == (uint32_t) start_ends_with);
break;
```

2020-08-31 16:08 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +  uint32_t pos = original_length;
This doesn't seem necessary.

2020-08-31 16:14 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +                                            ecma_string_t *search_str_p, /**< string's length */
Comments should be updated.

2020-08-31 16:14 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +    lit_utf8_decr (&end_p);
Please add a newline before this.

2020-09-07 12:36 UTC, dbatyai requested changes

2020-09-07 12:36 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +  const lit_utf8_byte_t  *current_p = end_p;
There should be only one whitespace after the type.

2020-09-07 12:36 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +    lit_utf8_decr (&end_p);
You should use `current_p` here.

2020-09-07 12:36 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +    lit_utf8_decr (&end_p);
This shold also be `current_p`.

2020-09-07 12:36 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +  }
The main logic could be enclosed in an `if (original_str_size >= search_str_size)` block, otherwise there's no need to search through the string.

2020-09-07 12:36 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +    if (end_p + search_str_size <= current_p
This first part of the condition could be removed, if you further adjust the starting search position before the main while loop.

```c
while (current_p + search_str_size > end_p)
{
  lit_utf8_decr (&current_p)
  position--;
}
```

2020-09-07 12:36 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +        ret_value = ecma_make_number_value (ECMA_NUMBER_MINUS_ONE);
The return value is minus one by default, you only need to change it if `index != UINT32_MAX`.

2020-09-07 12:36 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +      return ret_value;
This should be a `break`, then the string deref on line 673 is no longer needed.

2020-09-07 12:36 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +        && memcmp (end_p, search_str_utf8_p, search_str_size) == 0)
First arg should be `current_p`

2020-09-14 13:27 UTC, dbatyai requested changes

2020-09-14 13:27 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +    match_found = ecma_make_uint32_value (start_pos);
This line should be removed, the assignment result is not used.

2020-09-14 13:27 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
> +      ecma_value_t find_index = ecma_builtin_helper_string_find_index (original_str_p, search_str_p, start);
Please add a newline after this line.

2020-09-17 13:30 UTC, dbatyai approved these changes
LGTM

2020-09-17 13:38 UTC, rerobika approved these changes
LGTM

2020-09-17 13:38 UTC, merged