Refactor ecma_builtin_global_object_unescape
jerryscript-project/jerryscript pull request #4115
Opened 2020-08-07 10:17 UTC by szilagyiadam

based on ECMA-262 v11, B.2.1.2

Fixed tests from the exclude list:
  <test id="annexB/built-ins/unescape/four-ignore-bad-u.js"><reason></reason></test>
  <test id="annexB/built-ins/unescape/four.js"><reason></reason></test>
  <test id="annexB/built-ins/unescape/two.js"><reason></reason></test>

JerryScript-DCO-1.0-Signed-off-by: Adam Szilagyi aszilagy@inf.u-szeged.hu

2020-08-07 12:35 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-global.c
> +        for (uint8_t i = 0; i < 2; i++)
Please separate it into a helper funciton.

2020-08-28 08:40 UTC, rerobika approved these changes
LGTM

2020-08-28 11:08 UTC, dbatyai requested changes

2020-08-28 11:08 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-global.c
> +        ecma_builtin_global_object_unescape_helper (&input_curr_p, &chr, 5, true);
Why don't we increment `input_curr_p` before calling the unescape helper, the there's no need for the `unicode_sequence` argument.

2020-08-28 11:08 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-global.c
> +                                            uint8_t end, /**< loop end */
We should call this `char_count` or something similar.

2020-08-28 11:08 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-global.c
> +                                            ecma_char_t *result_c, /**< [out] character */
Why don't we return with this?

2020-08-28 11:08 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-global.c
> +    *buffer_p += unicode_sequence ? 5 : 2;
`*buffer_p += end;` (which will be renamed hopefully)

2020-08-28 11:08 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-global.c
> +    if (lit_char_is_hex_digit (*(*buffer_p + i)))
Why don't we do an early return when `!lit_char_is_hex_digit (...)`

2021-01-14 15:15 UTC, dbatyai approved these changes
LGTM

2021-01-14 15:16 UTC, merged