Added new default assert check in ecma_copy_value
jerryscript-project/jerryscript pull request #4168
Opened 2020-08-26 06:41 UTC by kisbg

fixes #4146

JerryScript-DCO-1.0-Signed-off-by: bence gabor kis kisbg@inf.u-szeged.hu

2020-08-26 13:52 UTC, rerobika requested changes

2020-08-26 13:52 UTC, rerobika commented on .github/workflows/gh-actions.yml
> +      SKIP_LIST: --skip-list=parser-oom.js,parser-oom2.js,stack-limit.js,regression-test-issue-2190.js,regression-test-issue-2258-2963.js,regression-test-issue-2448.js,regression-test-issue-2905.js,r
This definitely should not be skiplisted.

2020-08-26 13:52 UTC, rerobika commented on tests/jerry/es.next/regression-test-issue-4146.js
> +        for(var i = 0; i < 1024; i++){
reduce the 1024 to smaller value.

2020-08-27 07:43 UTC, rerobika requested changes

2020-08-27 07:43 UTC, rerobika commented on .github/workflows/gh-actions.yml
> -
Please revert this change.

2020-08-27 07:43 UTC, rerobika commented on tests/jerry/es.next/regression-test-issue-4146.js
> +assert (currArray.copyWithin(200, {valueOf: shorten}).length == 20)
Also please add an assert for the content of the array as well.

2020-08-27 13:45 UTC, rerobika commented on tests/jerry/es.next/regression-test-issue-4146.js
> +print (currArray.copyWithin(200, {valueOf: shorten}).equals (array))
print -> assert

2020-08-27 13:47 UTC, rerobika approved these changes
LGTM, just please squash the commits.

2020-08-28 08:54 UTC, galpeter approved these changes
lgtm

2020-08-28 08:55 UTC, merged