Refactor ecma_op_check_object_coercible
jerryscript-project/jerryscript pull request #4169
Opened 2020-08-26 07:42 UTC by szilagyiadam

The method returns bool now instead of an ecma_value_t

JerryScript-DCO-1.0-Signed-off-by: Adam Szilagyi aszilagy@inf.u-szeged.hu

2020-08-26 10:59 UTC, rerobika requested changes

2020-08-26 11:14 UTC, rerobika requested changes

2020-08-26 11:14 UTC, rerobika commented on jerry-core/vm/vm.c
> +
No new line is required.

2020-08-26 11:14 UTC, rerobika commented on jerry-core/ecma/operations/ecma-conversion.c
> + * @return bool
```
@return true - if the value can be coerced to object without any exceptions
        false - otherwise
```

2020-08-27 11:35 UTC, rerobika requested changes

2020-08-27 11:35 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-intrinsic.c
> +        return ecma_raise_type_error (ECMA_ERR_MSG ("Argument cannot be converted to an object."));
I'd keep the error raise in `ecma_op_require_object_coercible`

2020-08-28 09:38 UTC, rerobika approved these changes
LGTM for the change, just fix the missing renaming issue.

2020-08-28 11:12 UTC, dbatyai approved these changes
LGTM

2020-08-28 11:12 UTC, merged