Implement DataView.prototype.{set, get}Big{U}int64 methods
jerryscript-project/jerryscript pull request #4175
Opened 2020-08-28 09:09 UTC by szilagyiadam

The algorithms are based on:
- ECMA-262 v11, 24.3.4.5
- ECMA-262 v11, 24.3.4.6
- ECMA-262 v11, 24.3.4.15
- ECMA-262 v11, 24.3.4.16

JerryScript-DCO-1.0-Signed-off-by: Adam Szilagyi aszilagy@inf.u-szeged.hu

2020-08-28 09:15 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-dataview-prototype.inc.h
> +ROUTINE (LIT_MAGIC_STRING_SET_BIGUINT64, ECMA_DATAVIEW_PROTOTYPE_SET_BIGUINT64, 2, 1)
The length property should be `2` for setters. Please update the other methods as well.

2020-08-28 12:21 UTC, rerobika commented on tests/test262-esnext-excludelist.xml
>    <test id="built-ins/DataView/prototype/setBigInt64/return-abrupt-from-tobigint-value.js"><reason></reason></test>
Can you please check these 2 failing testcases?

2020-08-28 12:28 UTC, dbatyai requested changes

2020-08-28 12:28 UTC, dbatyai commented on jerry-core/ecma/operations/ecma-dataview-object.c
> +    if (!set_value_is_bigint)
The value should be coerced to a bigint, not just checked. In fact, it seems this whole method needs an update, as regular values should also be coerced to a number, and the coercion should happen much earlier.

2020-10-27 09:31 UTC, ossy-szeged commented
It is outdated and will be fixed in #4287 and #4315.

2020-10-27 09:31 UTC, closed without merging