Add new target support for object create
jerryscript-project/jerryscript pull request #4203
Opened 2020-09-18 11:14 UTC by kisbg

JerryScript-DCO-1.0-Signed-off-by: bence gabor kis kisbg@inf.u-szeged.hu

2020-09-18 12:05 UTC, zherczeg requested changes
Just minor things.

2020-09-18 12:05 UTC, zherczeg commented on jerry-core/ecma/builtin-objects/ecma-builtin-object.c
> +    return ecma_make_object_value (obj_p);
`return ecma_make_object_value (ecma_op_create_object_object_noarg ());`

2020-09-18 12:05 UTC, zherczeg commented on jerry-core/ecma/builtin-objects/ecma-builtin-object.c
> +    ecma_object_t *object_p = ecma_create_object (prototype_obj_p,
Please add a newline before this line.

2020-09-21 07:08 UTC, rerobika approved these changes
LGTM

2020-10-05 09:28 UTC, zherczeg requested changes

2020-10-05 09:28 UTC, zherczeg commented on jerry-core/ecma/builtin-objects/ecma-builtin-object.c
> +
Please don't add this newline.

2020-10-07 13:07 UTC, zherczeg approved these changes
LGTM

2020-10-07 13:07 UTC, merged