Add a new check for array.prototype.sort in array prototype dispatch
jerryscript-project/jerryscript pull request #4208
Opened 2020-09-21 13:45 UTC by kisbg

Bugfix: first check arguments callable then the length of the this value.

JerryScript-DCO-1.0-Signed-off-by: bence gabor kis kisbg@inf.u-szeged.hu

2020-09-22 10:58 UTC, rerobika requested changes

2020-09-22 10:58 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
> +      && !ecma_is_value_undefined (arguments_list_p[0])
Please rearrange this builtin id to not burden the common code path.

2020-09-24 07:07 UTC, rerobika requested changes

2020-09-24 07:07 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
> +  ecma_free_value (len_value);
This should not be released.

2020-10-05 09:22 UTC, zherczeg approved these changes
LGTM

2020-10-05 09:24 UTC, rerobika approved these changes
LGTM

2020-10-05 09:26 UTC, merged