Bound names of for-in/of statements cannot contain let
jerryscript-project/jerryscript pull request #4225
Opened 2020-09-23 14:03 UTC by dbatyai

2020-09-24 11:37 UTC, rerobika approved these changes
LGTM

2020-09-25 08:16 UTC, zherczeg requested changes

2020-09-25 08:16 UTC, zherczeg commented on jerry-core/parser/js/js-parser-statm.c
> +          parser_raise_error (context_p, PARSER_ERR_INVALID_IDENT);
What about using PARSER_ERR_LEXICAL_LET_BINDING ?

2020-09-25 12:18 UTC, zherczeg approved these changes
LGTM

2020-09-25 14:33 UTC, merged