Fix Symbol to Object comparision
jerryscript-project/jerryscript pull request #4226
Opened 2020-09-23 14:04 UTC by dbatyai

2020-09-24 11:36 UTC, rerobika approved these changes
LGTM

2020-09-24 11:39 UTC, ossy-szeged commented
LGTM (informal)

2020-09-25 08:09 UTC, zherczeg requested changes

2020-09-25 08:09 UTC, zherczeg commented on jerry-core/ecma/operations/ecma-comparison.c
> +    if (!ecma_is_value_object (y))
The other cases simply swapped the values.

2020-09-25 12:19 UTC, zherczeg approved these changes
LGTM

2020-09-28 14:01 UTC, merged