Error should be thrown later when calling super multiple times
jerryscript-project/jerryscript pull request #4256
Opened 2020-10-01 08:43 UTC by dbatyai

2020-10-01 08:56 UTC, rerobika requested changes

2020-10-01 08:56 UTC, rerobika commented on jerry-core/vm/vm.c
> +    const bool called_before = ecma_op_this_binding_is_initialized (prop_p);
As I see the this value is only binded at line 624 so it still remains uninitialized after the constructor call so saving this value unnecessary.

2020-10-01 13:50 UTC, rerobika approved these changes
LGTM

2020-10-09 12:10 UTC, galpeter approved these changes
lgtm

2020-10-10 16:58 UTC, merged