Check for prototype bound name in class static accessors
jerryscript-project/jerryscript pull request #4257
Opened 2020-10-01 08:44 UTC by dbatyai

2020-10-01 09:02 UTC, rerobika requested changes

2020-10-01 09:02 UTC, rerobika commented on jerry-core/parser/js/js-parser-expr.c
> +        if (lexer_compare_literal_to_string (context_p, "prototype", 9))
Can we ensure that the current literal is ident or string?

Also, as I see we should also throw error in the following case :
```js
class A {
  static get prototyp\u{0065}() {}
}
```

2020-10-01 10:14 UTC, zherczeg commented on jerry-core/parser/js/js-lexer.c
> +  JERRY_ASSERT (context_p->token.type == LEXER_LITERAL);
I think we should not change this function.

2020-10-01 13:51 UTC, rerobika commented
LGTM

2020-10-01 13:51 UTC, rerobika approved these changes
LGTM

2020-10-15 10:37 UTC, zherczeg requested changes

2020-10-15 10:37 UTC, zherczeg commented on tests/jerry/es.next/class.js
> +must_throw("class A { static set prototype() {} }");
I would add some testcases for the string variant as well:
`must_throw("class A { static get 'prototype'() {} }");`

2020-10-16 07:06 UTC, zherczeg approved these changes
LGTM

2020-10-16 07:07 UTC, zherczeg commented
Please resolve conflicts first, then you can land the patch.

2020-10-16 15:02 UTC, merged