Change guarding of ecma_is_value_bigint function
jerryscript-project/jerryscript pull request #4269
Opened 2020-10-02 11:05 UTC by orkvi

JerryScript-DCO-1.0-Signed-off-by: Virag Orkenyi orkvi@inf.u-szeged.hu

2020-10-02 11:23 UTC, rerobika requested changes

2020-10-02 11:23 UTC, rerobika commented on jerry-core/ecma/base/ecma-helpers-value.c
> +  #endif /* ENABLED (JERRY_BUILTIN_BIGINT) */
Now you can remove `ECMA_CHECK_BIGINT_IN_ASSERT`.

Also this whole can can be performed for `ecma_is_value_symbol` as well. (same for ECMA_CHECK_SYMBOL_IN_ASSERT)

2020-10-05 08:37 UTC, rerobika approved these changes
LGTM

2020-10-05 12:42 UTC, dbatyai approved these changes
LGTM

2020-10-05 12:43 UTC, merged