Fix assertion fail in typedarray_prototype_to locale_string
jerryscript-project/jerryscript pull request #4285
Opened 2020-10-12 07:35 UTC by orkvi

Change typedarray_prototype_to_locale_string_helper to use ecma_op_invoke_magic_id instead

Fixes #4217 

JerryScript-DCO-1.0-Signed-off-by: Virag Orkenyi orkvi@inf.u-szeged.hu

2020-10-12 11:05 UTC, rerobika requested changes

2020-10-12 11:05 UTC, rerobika commented on jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c
>    ecma_value_t ret_value = ECMA_VALUE_EMPTY;
This variable is not needed anymore.

2020-10-12 11:05 UTC, rerobika commented on jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c
> +  ret_value = ecma_make_string_value (str_p);
return with `ecma_make_string_value` directly.

2020-10-16 10:45 UTC, rerobika approved these changes
LGTM

2020-10-22 10:49 UTC, dbatyai approved these changes
LGTM

2020-10-22 10:49 UTC, merged