Fix the indexing problem in typedarray_prototype_index_of & last_index_of.
jerryscript-project/jerryscript pull request #4305
Opened 2020-10-21 11:02 UTC by orkvi

JerryScript-DCO-1.0-Signed-off-by: Virag Orkenyi orkvi@inf.u-szeged.hu

2020-10-26 08:29 UTC, rerobika requested changes

2020-10-26 08:29 UTC, rerobika commented on jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c
> +
Do not remove this line.

2020-10-26 08:29 UTC, rerobika commented on jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c
> +  //uint32_t limit = info_p->length * info_p->element_size;
Remove this comment.

2020-10-26 08:29 UTC, rerobika commented on jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c
> +    ecma_op_to_integer (args[1], &to_int);
This operation can throw an error. Please handle it.

2020-11-02 08:40 UTC, rerobika approved these changes
LGTM

2020-11-16 14:43 UTC, dbatyai approved these changes
LGTM

2020-11-16 14:43 UTC, merged