Add Boolean Prototype Dispatcher
jerryscript-project/jerryscript pull request #4308
Opened 2020-10-22 10:58 UTC by Yuyupo

JerryScript-DCO-1.0-Signed-off-by: Daniella Barsony bella@inf.u-szeged.hu

2020-10-22 11:03 UTC, dbatyai requested changes

2020-10-22 11:03 UTC, dbatyai commented on jerry-core/ecma/builtin-objects/ecma-builtin-boolean-prototype.c
> +
Please remove this newline.

2020-10-22 11:14 UTC, rerobika requested changes

2020-10-22 11:14 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-boolean-prototype.c
> +  switch (builtin_routine_id)
```c
ecma_value_t value_of_ret = ecma_builtin_boolean_prototype_object_value_of (this_arg);

if (id == ECMA_BOOLEAN_PROTOTYPE_ROUTINE_VALUE_OF) return value_of_ret;

perform toString operation.
```

So no switch is needed.

2020-10-22 12:44 UTC, dbatyai approved these changes
LGTM

2020-10-22 12:49 UTC, zherczeg requested changes

2020-10-22 12:49 UTC, zherczeg commented on jerry-core/ecma/builtin-objects/ecma-builtin-boolean-prototype.c
> +  if (ECMA_IS_VALUE_ERROR (value_of_ret))
There should be an assert before this if.
`JERRY_ASSERT (builtin_routine_id == ECMA_BOOLEAN_PROTOTYPE_ROUTINE_TO_STRING);`

2020-10-26 08:03 UTC, rerobika approved these changes
LGTM

2020-10-27 08:43 UTC, rerobika requested changes

2020-10-27 08:43 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-boolean-prototype.c
> +  JERRY_ASSERT (ecma_is_value_boolean (value_of_ret));
`ecma_is_value_boolean` -> `ecma_is_value_false`

2020-10-29 08:22 UTC, rerobika approved these changes
LGTM

2020-10-29 11:24 UTC, zherczeg approved these changes
LGTM

2020-10-29 11:24 UTC, merged