Add Promise Prototype Dispatcher
jerryscript-project/jerryscript pull request #4309
Opened 2020-10-22 11:02 UTC by Yuyupo

JerryScript-DCO-1.0-Signed-off-by: Daniella Barsony bella@inf.u-szeged.hu

2020-10-26 08:06 UTC, rerobika requested changes

2020-10-26 08:06 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-promise-prototype.c
> +      return ecma_promise_then (this_arg, arguments_list_p[0], arguments_list_p[1]);
Accessing directly args_p[0] is unsafe. Check argc first.

2020-10-27 08:40 UTC, rerobika requested changes

2020-10-27 08:40 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-promise-prototype.c
> +      return ecma_promise_then (this_arg, argument, arguments_list_p[1]);
ditto, accessing `arguments_list_p[1]` directly is unsafe

2020-10-28 14:06 UTC, rerobika approved these changes
LGTM

2020-10-28 14:09 UTC, zherczeg approved these changes
LGTM

2020-10-28 14:09 UTC, merged