Add Array Builtin Dispatcher
jerryscript-project/jerryscript pull request #4310
Opened 2020-10-22 11:34 UTC by Yuyupo

JerryScript-DCO-1.0-Signed-off-by: Daniella Barsony bella@inf.u-szeged.hu

2020-10-26 08:30 UTC, rerobika requested changes

2020-10-26 08:30 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-array.c
> +      return ecma_is_value_array (arguments_list_p[0]);
`return arguments_number > 0 ? ecma_is_value_array (arguments_list_p[0]) : ECMA_VALUE_FALSE`

2020-10-27 08:39 UTC, rerobika approved these changes
lgtm

2020-10-29 09:49 UTC, dbatyai approved these changes
LGTM

2020-10-29 09:49 UTC, merged