Add new target support for ArrayBuffer and TypedArray
jerryscript-project/jerryscript pull request #4369
Opened 2020-12-16 13:42 UTC by kisbg

JerryScript-DCO-1.0-Signed-off-by: bence gabor kis kisbg@inf.u-szeged.hu

2020-12-18 08:18 UTC, zherczeg approved these changes
LGTM

2020-12-18 09:02 UTC, rerobika requested changes

2021-01-11 12:03 UTC, rerobika requested changes

2021-01-11 12:03 UTC, rerobika commented on jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-helpers.c
> +                                                              ecma_typedarray_helper_get_prototype_id (typedarray_id));
Save proto_id into a local variable.

2021-01-11 12:39 UTC, rerobika commented on jerry-core/ecma/operations/ecma-arraybuffer-object.c
> +  if (!ECMA_IS_VALUE_ERROR (ecma_make_object_value (array_buffer)))
This operation cannot fail. So this check is unnecessary.

2021-01-11 12:45 UTC, kisbg commented
@rerobika Thank you for the review!

2021-01-11 13:02 UTC, rerobika approved these changes
LGTM

2021-01-11 13:20 UTC, merged