only tools/packaging/test262.py force using python2.
jerryscript-project/jerryscript pull request #4379
Opened 2020-12-28 17:34 UTC by lygstate

JerryScript-DCO-1.0-Signed-off-by: Yonggang Luo luoyonggang@gmail.com

2020-12-29 01:56 UTC, akosthekiss requested changes

2020-12-29 01:56 UTC, akosthekiss commented on tools/runners/run-test-suite-test262.py
> +def get_platform_cmd_prefix(is_python2: False):
This isn't valid Python syntax.

2020-12-29 04:45 UTC, lygstate commented on tools/runners/run-test-suite-test262.py
> +def get_platform_cmd_prefix(is_python2: False):
fixed

2020-12-30 10:40 UTC, ossy-szeged commented
It looks good, just a note, it depends on #4381

2020-12-30 16:23 UTC, closed without merging