Implement Jerry api get builtin object
jerryscript-project/jerryscript pull request #4453
Opened 2021-01-12 11:49 UTC by kisbg

JerryScript-DCO-1.0-Signed-off-by: bence gabor kis kisbg@inf.u-szeged.hu

2021-01-12 13:29 UTC, zherczeg requested changes

2021-01-12 13:29 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> +*New in version [[NEXT_RELEASE]]*.
I think this line should be below

2021-01-12 13:29 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> +  jerry_value_t array_prototype = jerry_get_builtin_object (JERRY_BUILTIN_ARRAY_PROTOTYPE_OBJECT);
Free the returned value.

2021-01-12 13:29 UTC, zherczeg commented on jerry-core/api/jerry.c
> +
Increase reference count, and remove the extra newline.

2021-01-12 13:29 UTC, zherczeg commented on jerry-core/api/jerry.c
> +jerry_value_t jerry_get_builtin_object (uint8_t builtin_id  /**< id of the  builtin */)
Wrong `)`, should be before the comment.

2021-01-12 13:29 UTC, zherczeg commented on jerry-core/api/jerry.c
> + *
Delete this line

2021-01-12 13:29 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> +Get the builtin object.
Better description: `Get the specified built-in object. The function always returns with an object, unless the feature required for the built-in object is disabled.`

2021-01-12 13:29 UTC, zherczeg commented on jerry-core/api/jerry.c
> +  JERRY_ASSERT (sizeof (jerry_builtin_id) / sizeof (uint8_t) >= builtin_id);
Check this with an `if`, and throw an error for invalid id-s.

2021-01-12 13:29 UTC, zherczeg commented on jerry-core/api/jerry.c
> +    return jerry_throw (ecma_raise_type_error (ECMA_ERR_MSG ("builtin are disabled.")));
disabled built-in

2021-01-12 13:29 UTC, zherczeg commented on tests/unit-core/test-api-get_builtin_object.c
> +  jerry_value_t array_prototype = jerry_get_builtin_object (JERRY_BUILTIN_ARRAY_PROTOTYPE_OBJECT);
Relese the value.

2021-01-12 15:00 UTC, rerobika requested changes

2021-01-13 08:44 UTC, kisbg commented
@zherczeg  Thank you for the review!

2021-01-13 08:49 UTC, kisbg commented on jerry-core/api/jerry.c
> +static const uint8_t jerry_builtin_id[13] =
Thanks, keep me updated when the patch is landed, and im going to rebase this pull request based on your work!

2021-01-19 12:38 UTC, closed without merging

2021-01-21 14:00 UTC, zherczeg commented
This api would be great for #4522. We should revive it.