Fix the return_abrupt problem in typedarray_prototype_join
jerryscript-project/jerryscript pull request #4635
Opened 2021-03-22 19:12 UTC by orkvi

JerryScript-DCO-1.0-Signed-off-by: Virag Orkenyi orkvi@inf.u-szeged.hu

2021-03-25 04:50 UTC, zherczeg approved these changes
LGTM

2021-03-29 11:45 UTC, galpeter requested changes
A minor change request.

2021-03-29 11:45 UTC, galpeter commented on jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c
>    uint32_t length = ecma_number_to_uint32 (length_number);
If I understand the code correctly we could also free the `length_value` here. After this point it is only released and not used in any other ways.

2021-06-15 13:57 UTC, galpeter approved these changes
lgtm

2021-08-30 12:02 UTC, rerobika commented
please rebase

2021-11-26 12:53 UTC, closed without merging