Continue replacing duplicate ecma definitions
jerryscript-project/jerryscript pull request #4644
Opened 2021-04-06 11:43 UTC by Achie72

JerryScript-DCO-1.0-Signed-off-by: Bela Toth tbela@inf.u-szeged.hu

2021-04-07 07:21 UTC, zherczeg requested changes

2021-04-07 07:21 UTC, zherczeg commented on jerry-core/ecma/base/ecma-gc.c
> +    if (JERRY_CONTEXT (JERRY_PROP_hashmap_alloc_state) > JERRY_PROP_HASHMAP_ALLOC_ON)
The name of a variable should not be changed. Similar cases below.

2021-04-07 07:21 UTC, zherczeg commented on jerry-core/ecma/base/ecma-helpers-string.c
> +JERRY_PROP_name_is_symbol (ecma_string_t *string_p) /**< ecma-string */
Also wrong.

2021-04-09 09:18 UTC, zherczeg requested changes
Better

2021-04-09 09:18 UTC, zherczeg commented on jerry-core/ecma/base/ecma-globals.h
> +#define JERRY_PROP_HASHMAP_ALLOC_ON 0
These should not be changed, only those which are defined in jerryscript-types.h

2021-04-14 10:47 UTC, zherczeg approved these changes
LGTM

2021-04-19 11:38 UTC, rerobika approved these changes

2021-04-19 11:44 UTC, merged