Add custom dispatcher to builtin_string
jerryscript-project/jerryscript pull request #4661
Opened 2021-04-23 19:14 UTC by orkvi

JerryScript-DCO-1.0-Signed-off-by: Virag Orkenyi orkvi@inf.u-szeged.hu

2021-04-23 19:36 UTC, rerobika requested changes

2021-04-23 19:36 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-string.c
> +      return ecma_builtin_string_object_raw (this_arg, arguments_list_p, arguments_number);
argument this is all unused in all these three functions, and the behavior is same when no arguments is passed. This common part should be the part of the dispatcher

2021-05-25 05:34 UTC, zherczeg requested changes
Only minor things.

2021-05-25 05:34 UTC, zherczeg commented on jerry-core/ecma/builtin-objects/ecma-builtin-string.c
> -  JERRY_UNUSED (this_arg);
Remove newline below.

2021-05-25 05:34 UTC, zherczeg commented on jerry-core/ecma/builtin-objects/ecma-builtin-string.c
> -  JERRY_UNUSED (this_arg);
Ditto.

2021-05-25 05:34 UTC, zherczeg commented on jerry-core/ecma/builtin-objects/ecma-builtin-string.c
> +  JERRY_UNUSED (this_arg);
Put a newline after this line.

2021-05-26 06:28 UTC, zherczeg requested changes

2021-05-26 06:28 UTC, zherczeg commented on jerry-core/ecma/builtin-objects/ecma-builtin-string.c
Remove this newline.

2021-05-26 09:15 UTC, zherczeg approved these changes
LGTM

2021-06-15 13:54 UTC, galpeter approved these changes
lgtm

2021-06-24 13:40 UTC, rerobika approved these changes

2021-06-24 13:40 UTC, merged