Add some new types
jerryscript-project/jerryscript pull request #4677
Opened 2021-05-21 11:45 UTC by gergocs

new types: JERRY_OBJECT_TYPE_NAMESPACE, JERRY_OBJECT_TYPE_MODULE, JERRY_OBJECT_TYPE_PROMISE, JERRY_OBJECT_TYPE_DATAVIEW, JERRY_OBJECT_TYPE_SITERATOR, JERRY_OBJECT_TYPE_ERROR, JERRY_OBJECT_TYPE_ARRAYBUFF

2021-05-25 05:43 UTC, zherczeg requested changes
Documentation update is missing.

2021-05-25 05:43 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> + - JERRY_OBJECT_TYPE_NAMESPACE - Namespace object
Module namespace object
(I think module is an important info here)

2021-05-25 05:43 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> + - JERRY_OBJECT_TYPE_SITERATOR - String iterator object
SITERATOR :)
Iterator is iterator, `jerry_iterator_get_type` should provide more detailed info.

2021-05-25 05:43 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> +jerry_value_is_true (const jerry_value_t value);
This should be in a different patch.

2021-05-26 06:33 UTC, zherczeg requested changes
You need to add API tests for testing these types.

2021-05-26 06:33 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> + - JERRY_OBJECT_TYPE_ARRAYBUFF - Array buffer object
Maybe this could be JERRY_OBJECT_TYPE_ARRAYBUFFER. No need for abbreviation.

2021-05-27 11:47 UTC, zherczeg requested changes

2021-05-27 11:47 UTC, zherczeg commented on tests/unit-core/test-api-objecttype.c
> +  jerry_module_link (module, NULL, NULL);
`jerry_release_value (jerry_module_link (module, NULL, NULL))`

2021-05-27 11:47 UTC, zherczeg commented on tests/unit-core/test-api-objecttype.c
> +    ENTRY_IF (JERRY_OBJECT_TYPE_ARRAYBUFFER, jerry_create_arraybuffer (10), JERRY_FEATURE_DATAVIEW),
jerry_create_arraybuffer depends on dataview?

2021-05-27 11:47 UTC, zherczeg commented on tests/unit-core/test-api-objecttype.c
> +    ENTRY_IF (JERRY_OBJECT_TYPE_DATAVIEW, jerry_create_dataview(jerry_create_arraybuffer (10), 0, 4), JERRY_FEATURE_DATAVIEW),
result of jerry_create_arraybuffer is not freed

2021-05-27 11:47 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> + - JERRY_OBJECT_TYPE_NAMESPACE - Module namespace object
JERRY_OBJECT_TYPE_MODULE_NAMESPACE

2021-05-31 07:32 UTC, zherczeg requested changes

2021-05-31 07:32 UTC, zherczeg commented on tests/unit-core/test-api-objecttype.c
> +  jerry_value_t module = jerry_parse ((const jerry_char_t *) "", 0, (&module_parse_options));
`(&module_parse_options)` -> `&module_parse_options`

2021-05-31 07:32 UTC, zherczeg commented on tests/unit-core/test-api-objecttype.c
> +  jerry_value_t modulelinked = jerry_module_link (module, NULL, NULL);
module_linked

2021-05-31 07:32 UTC, zherczeg commented on tests/unit-core/test-api-objecttype.c
> +  jerry_value_t dataview = jerry_create_dataview (arraybuffer, 0, 4);
Move this to a helper function (similar to test_namespace)

2021-05-31 12:21 UTC, zherczeg approved these changes
LGTM

2021-05-31 12:22 UTC, rerobika approved these changes

2021-05-31 12:24 UTC, merged