Add custom dispatcher to builtin-json.
jerryscript-project/jerryscript pull request #4679
Opened 2021-05-24 17:30 UTC by orkvi

JerryScript-DCO-1.0-Signed-off-by: Orkenyi Virag orkvi@inf.u-szeged.hu

2021-05-25 05:36 UTC, zherczeg requested changes
Only minor things.

2021-05-25 05:36 UTC, zherczeg commented on jerry-core/ecma/builtin-objects/ecma-builtin-json.c
> -  JERRY_UNUSED (this_arg);
Remove newline after this. You did it right in the seocnd case.

2021-05-25 05:36 UTC, zherczeg commented on jerry-core/ecma/builtin-objects/ecma-builtin-json.c
> +  ecma_value_t arg2 = (arguments_number > 2)? arguments_list_p[2]:ECMA_VALUE_UNDEFINED;
Syntax is incorrect, put spaces around ? and :

2021-05-26 06:27 UTC, zherczeg approved these changes
LGTM

2021-06-15 13:18 UTC, galpeter requested changes

2021-06-15 13:18 UTC, galpeter commented on jerry-core/ecma/builtin-objects/ecma-builtin-json.c
> +                                     uint32_t arguments_number) /**< length of arguments' list */
Incorrect indentation

2021-06-15 13:18 UTC, galpeter commented on jerry-core/ecma/builtin-objects/ecma-builtin-json.c
> +  ecma_value_t arg2 = (arguments_number > 2) ? arguments_list_p[2] : ECMA_VALUE_UNDEFINED;
To keep it in sync with the methods (parse, stringify) we should start the naming from 1 (arg0 should be arg1, etc..)

2021-06-18 14:17 UTC, galpeter approved these changes
lgtm

2021-07-20 09:32 UTC, merged