Remove get_boolean_value
jerryscript-project/jerryscript pull request #4685
Opened 2021-06-05 06:09 UTC by gergocs

JerryScript-DCO-1.0-Signed-off-by: Gergo Csizi csgergo92@gmail.com

2021-06-05 08:02 UTC, zherczeg requested changes

2021-06-05 08:02 UTC, zherczeg commented on tests/unit-core/test-api.c
> +  TEST_ASSERT (jerry_value_is_true (res) && jerry_value_is_true (res));
Don't duplicate `jerry_value_is_true`

2021-06-05 08:02 UTC, zherczeg commented on tests/unit-core/test-internal-properties.c
> +  TEST_ASSERT (jerry_value_is_boolean (has_result_1) && jerry_value_is_true (has_result_1));
`jerry_value_is_boolean` is unnecessary, but it is part of an assert, so we might keep it.

2021-06-05 17:54 UTC, zherczeg approved these changes
LGTM

2021-06-24 13:37 UTC, rerobika approved these changes

2021-06-24 13:40 UTC, merged