Add custom dispatcher to builtin_weakref_prototype.
jerryscript-project/jerryscript pull request #4686
Opened 2021-06-08 09:34 UTC by orkvi

JerryScript-DCO-1.0-Signed-off-by: Orkenyi Virag orkvi@inf.u-szeged.hu

2021-06-15 13:49 UTC, galpeter requested changes

2021-06-15 13:49 UTC, galpeter commented on jerry-core/ecma/builtin-objects/ecma-builtin-weakref-prototype.c
> +                                                        uint32_t arguments_number) /**< length of arguments' list */
Incorrect indentation.

2021-06-18 14:17 UTC, galpeter approved these changes
lgtm

2021-06-24 13:36 UTC, rerobika approved these changes

2021-06-24 13:36 UTC, merged