Add custom dispatcher to error-prototype
jerryscript-project/jerryscript pull request #4692
Opened 2021-06-24 10:45 UTC by orkvi

JerryScript-DCO-1.0-Signed-off-by: Orkenyi Virag orkvi@inf.u-szeged.hu

2021-06-24 13:35 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-error-prototype.c
> +                                                                                     *   list */
misaligned parameters

2021-06-28 13:33 UTC, zherczeg requested changes

2021-06-28 13:33 UTC, zherczeg commented on jerry-core/ecma/builtin-objects/ecma-builtin-error-prototype.c
> +                                                                                                 *   passed to
No need to split a comment to 3 lines when there is enough space. Try to reduce these.

2021-07-07 07:46 UTC, rerobika requested changes

2021-07-07 07:46 UTC, rerobika commented on jerry-core/ecma/builtin-objects/ecma-builtin-error-prototype.c
> +  * Dispatcher of the Generator built-in's routines
misaligned comment block, also it's not Generator builtin object.

2021-07-20 09:18 UTC, galpeter approved these changes
lgtm

2021-07-20 09:32 UTC, zherczeg approved these changes
LGTM

2021-08-03 09:09 UTC, rerobika approved these changes

2021-08-03 09:09 UTC, merged