Implement container operators API function
jerryscript-project/jerryscript pull request #4697
Opened 2021-06-29 06:36 UTC by Achie72

Basically re-opening and updating #4275

Co-authored-by: bence gabor kis <kisbg@inf.u-szeged.hu>
JerryScript-DCO-1.0-Signed-off-by: Bela Toth tbela@inf.u-szeged.hu

2021-07-15 05:57 UTC, zherczeg requested changes

2021-07-15 05:57 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> +   - jerry value - otherwise
```
  - result, if the operation is successful
  - error, otherwise
```

2021-07-15 05:57 UTC, zherczeg commented on jerry-core/api/jerry.c
> +      if (operation == JERRY_CONTAINER_OP_SET)
This could be combined with the check above. But it would be better if you would check the allowed operations, because that is easier to maintain.

2021-07-15 05:57 UTC, zherczeg commented on jerry-core/api/jerry.c
> +      if (ecma_is_value_error_reference (arguments[0]))
`ecma_is_value_error_reference (arguments[0]) || ecma_is_value_error_reference (arguments[1])`

2021-07-15 05:57 UTC, zherczeg commented on jerry-core/api/jerry.c
> +    if (type == LIT_MAGIC_STRING_WEAKSET_UL && operation == JERRY_CONTAINER_OP_CLEAR)
Why these are not combined with one check:
```
if ((type == LIT_MAGIC_STRING_SET_UL || type == LIT_MAGIC_STRING_WEAKSET_UL)
    && (operation == JERRY_CONTAINER_OP_GET
        || operation == JERRY_CONTAINER_OP_SET
        || (type == LIT_MAGIC_STRING_WEAKSET_UL && operation == JERRY_CONTAINER_OP_CLEAR))
{
...
}
```
Similar case below.

2021-07-15 05:57 UTC, zherczeg commented on jerry-core/include/jerryscript-core.h
> +typedef enum
These should go into jerryscript-types.h

2021-07-19 11:36 UTC, zherczeg approved these changes
LGTM

2021-07-19 13:10 UTC, DanielBallaSZTE reviewed
Just some minor things

2021-07-19 13:10 UTC, DanielBallaSZTE commented on jerry-core/api/jerry.c
> +  return jerry_throw (ecma_raise_type_error (ECMA_ERR_MSG ("Container is not an object.")));
Same here.

2021-07-19 14:04 UTC, Achie72 commented on jerry-core/api/jerry.c
> +    return jerry_throw (ecma_raise_type_error (ECMA_ERR_MSG ("Container is not an object.")));
I'm not sure how to phrase this message correctly, updated it with something, but i'm looking for any advice if you have a better one for it.

2021-07-20 11:08 UTC, DanielBallaSZTE approved these changes

2021-07-27 10:24 UTC, rerobika approved these changes

2021-07-27 10:25 UTC, merged