Merge Map and Set Guards with Container
jerryscript-project/jerryscript pull request #4709
Opened 2021-07-07 13:01 UTC by Achie72

Remove JERRY_BUILTIN_MAP/SET/WEAKMAP/WEAKSET
and replace them with JERRY_BUILTIN_CONTAINER.

JerryScript-DCO-1.0-Signed-off-by: Bela Toth tbela@inf.u-szeged.hu

2021-07-08 04:08 UTC, zherczeg requested changes
Good patch, only some minor changes.

2021-07-08 04:08 UTC, zherczeg commented on jerry-core/config.h
> -|| (JERRY_BUILTIN_WEAKREF == 1) \
Don't remove weakref

2021-07-08 04:08 UTC, zherczeg commented on jerry-core/ecma/builtin-objects/ecma-builtin-global.inc.h
> +OBJECT_VALUE (LIT_MAGIC_STRING_WEAKSET_UL,
This code added twice. Is this correct?

2021-07-08 04:08 UTC, zherczeg commented on jerry-core/ecma/operations/ecma-objects.c
> +#if JERRY_BUILTIN_CONTAINER
It seems these could be merged together (by removing this two line).

2021-07-08 04:08 UTC, zherczeg commented on jerry-core/ecma/operations/ecma-objects.c
> +#if JERRY_BUILTIN_CONTAINER
Ditto.

2021-07-12 07:13 UTC, zherczeg requested changes

2021-07-12 07:13 UTC, zherczeg commented on jerry-core/api/jerry.c
> -#if JERRY_BUILTIN_WEAKREF
Don't remove this.

2021-07-12 07:13 UTC, zherczeg commented on jerry-core/ecma/base/ecma-gc.c
> +#if JERRY_BUILTIN_CONTAINER
Keep `|| JERRY_BUILTIN_WEAKREF`

2021-07-12 08:08 UTC, zherczeg approved these changes
LGTM with minor change

2021-07-12 08:08 UTC, zherczeg commented on jerry-core/config.h
> +#ifndef JERRY_BUILTIN_CONTAINER
Maybe this could be moved up to its lexicographic place.

2021-07-12 09:09 UTC, rerobika approved these changes

2021-07-12 09:20 UTC, merged