Rework external arraybuffer and shared arraybuffer free operation
jerryscript-project/jerryscript pull request #4744
Opened 2021-08-23 12:36 UTC by gergocs

JerryScript-DCO-1.0-Signed-off-by: Gergo Csizi csgergo92@gmail.com

2021-08-23 13:43 UTC, galpeter requested changes

2021-08-23 13:43 UTC, galpeter commented on docs/02.API-REFERENCE.md
> +*Changed in version [[NEXT_RELEASE]]*: `free_cb` is replaced by `user_p`.
As this is already a new function (which is in any release yet), there is no need for both the "new in version  [[next_release]]" and "changed in [[new_release]]" entries. Just keep the "new in version..." one.

2021-08-23 13:43 UTC, galpeter commented on jerry-core/ecma/base/ecma-gc.c
> +            if (array_p->user_p != NULL)
Incorrect check, the `free_cb` must be checked (just as before) otherwise we could call the free_cb if it is NULL.

2021-08-23 13:43 UTC, galpeter commented on jerry-core/ecma/operations/ecma-arraybuffer-object.c
> +  }
Why do we need to call the free_cb when creating an external array buffer?

2021-08-23 13:43 UTC, galpeter commented on jerry-core/ecma/operations/ecma-shared-arraybuffer-object.c
> +
Same question as for the "normal" array buffer.

2021-08-23 13:43 UTC, galpeter commented on docs/02.API-REFERENCE.md
> +- `length` - extrenal buffer length
What does the "external buffer length" mean? Number of bytes? Number of elements?

2021-08-23 13:43 UTC, galpeter commented on docs/02.API-REFERENCE.md
> +Sets the global callback which is called when the arraybuffer is no longer used.
(imho) A bit of improvement " when the arraybuffer" -> "when an external arraybuffer is released / freed"

2021-08-23 13:43 UTC, galpeter commented on docs/02.API-REFERENCE.md
> +static void
Missing empty line before the method.

2021-08-23 13:43 UTC, galpeter commented on docs/02.API-REFERENCE.md
> +int
ditto

2021-08-23 13:43 UTC, galpeter commented on docs/02.API-REFERENCE.md
> +  jerry_release_value (external_arraybuffer);
This is a dangerous example as we are passing a stack local memory region for the external arraybuffer. For this example we should use "malloc" and "free" (and not VLA)

2021-08-23 13:43 UTC, galpeter commented on docs/02.API-REFERENCE.md
> +*New in version [[NEXT_RELEASE]]*.
Duplicate "new in.." entry. Remove this one.

2021-08-23 13:43 UTC, galpeter commented on tests/unit-core/test-arraybuffer.c
> +  JERRY_UNUSED (buffer);
This seems strange: if the "free" call is removed where will be the "buffer" freed?

2021-08-23 13:43 UTC, galpeter commented on tests/unit-core/test-arraybuffer.c
>      uint8_t *buf = (uint8_t *) malloc (length);
AFAIK: this malloc does not have a "free" pair. (see comment above)

2021-08-24 12:35 UTC, gergocs commented
Patch is ready for review

2021-08-30 07:20 UTC, zherczeg commented on jerry-core/ecma/operations/ecma-arraybuffer-object.c
> +      free_cb (array_p->extended_object.u.cls.u3.length, array_p->buffer_p, array_p->user_p);
Yes.

2021-08-30 12:51 UTC, rerobika requested changes

2021-08-30 12:51 UTC, rerobika commented on docs/02.API-REFERENCE.md
> +*Note*:
this request is still valid.

2021-08-30 12:51 UTC, rerobika commented on docs/02.API-REFERENCE.md
> +  uint8_t *buffer_p = (uint8_t *)malloc (sizeof(uint8_t) * buffer_size);
this request is still valid.

2021-08-30 12:51 UTC, rerobika commented on docs/02.API-REFERENCE.md
> +  uint8_t *buffer_p = (uint8_t *)malloc (sizeof(uint8_t) * buffer_size);
also after sizeof

2021-08-31 06:45 UTC, gergocs commented
Patch is ready for review

2021-08-31 08:12 UTC, zherczeg requested changes
Mostly good, the testing needs to be improved.

2021-08-31 08:12 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> +  /* The external_arraybuffer_free_callback is called. */
comment: The external_arraybuffer_free_callback is called eventually by the garbage collector.

2021-08-31 08:12 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> +After the object is not needed the GC will call the callback which can be set by
GC -> garbage collector

2021-08-31 08:12 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> +After the object is not needed the GC will call the callback which can be set with
GC -> garbage collector

2021-08-31 08:12 UTC, zherczeg commented on jerry-core/api/jerry.c
> +    shared_arraybuffer = ecma_arraybuffer_new_object_external (size, buffer_p, user_p);
Why this is changed to non-shared?

2021-08-31 08:12 UTC, zherczeg commented on tests/unit-core/test-arraybuffer.c
> +static bool user_callback_called = false;
the type of this should be change to `int`, and the appropriate number of calls should be checked later. Same for `callback_called `

2021-08-31 08:12 UTC, zherczeg commented on tests/unit-core/test-arraybuffer.c
> +  JERRY_UNUSED (user_p);
the length and user_p should be checked in some way. e.g. length should be 15 or its other values, and user_p could be compared to some global values.

2021-08-31 08:12 UTC, zherczeg commented on tests/unit-core/test-arraybuffer.c
> +    jerry_detach_arraybuffer (input_buffer);
The callback should be checked after this

2021-09-01 08:53 UTC, gergocs commented
Patch is ready for review

2021-09-01 12:52 UTC, zherczeg requested changes

2021-09-01 12:52 UTC, zherczeg commented on docs/02.API-REFERENCE.md
> +  /* The external_arraybuffer_free_callback is called eventually by the garbage collector */
Full stop after the sentence

2021-09-01 12:52 UTC, zherczeg commented on tests/unit-core/test-arraybuffer.c
> +    jerry_gc (JERRY_GC_PRESSURE_LOW);
JERRY_GC_PRESSURE_HIGH should be used to avoid future optimizations

2021-09-01 12:52 UTC, zherczeg commented on tests/unit-core/test-arraybuffer.c
> +    jerry_detach_arraybuffer (input_buffer);
It seems it is still not checked

2021-09-01 12:52 UTC, zherczeg commented on tests/unit-core/test-arraybuffer.c
> +    TEST_ASSERT (callback_called == 3);
This value should be checked frequently

2021-09-01 12:52 UTC, zherczeg commented on tests/unit-core/test-arraybuffer.c
>  static bool detach_free_callback_called = false;
The detach_free_callback_called should be deleted and callback_called should be used instead

2021-09-01 12:52 UTC, zherczeg commented on tests/unit-core/test-arraybuffer.c
> +    external_buffer_size = 8;
Probably you can reset callback_called to 0 here as well, and test its values

2021-09-02 12:28 UTC, gergocs commented
Patch is ready for review

2021-09-02 14:45 UTC, zherczeg approved these changes
LGTM

2021-10-20 13:57 UTC, rerobika commented
@galpeter PTAL.

2021-10-20 15:06 UTC, zherczeg commented
I am also working on something which affects the allocation, so this might be obsolote now.

2021-11-24 16:19 UTC, rerobika commented
Can we close this PR?

2021-11-25 18:33 UTC, closed without merging