Implement 'hasOwn' routine of Object object
jerryscript-project/jerryscript pull request #4835
Opened 2021-11-24 14:14 UTC by repasics

JerryScript-DCO-1.0-Signed-off-by: Csaba Repasi repasics@inf.u-szeged.hu

2021-11-24 16:02 UTC, rerobika requested changes

2021-11-24 16:02 UTC, rerobika commented on tests/jerry/es.next/object-hasown.js
> +
please add test for Object.hasOwn.call(undefined), and `Object.hasOwn.call({}, {get toString() { throw new Error()}})`

2021-11-24 16:12 UTC, galpeter commented on jerry-core/api/jerryscript.c
> +#endif /* JERRY_BUILTIN_PROXY || JERRY_BUILTIN_TYPEDARRAY */
AFAIK we could simplify this to:
```c
return jerry_return(ecma_op_object_has_own_property(...));
```
I don't think the skipping of `jerry_return` call worth the extra #if-def guard.

2021-11-24 18:03 UTC, zherczeg commented
It does not fix any test262 tests, is it a new standard?

2021-11-25 09:12 UTC, rerobika commented
> It does not fix any test262 tests, is it a new standard?

We need to update the test262 runner to the latest master. cc @ossy-szeged

2021-12-10 14:32 UTC, rerobika requested changes

2021-12-10 14:32 UTC, rerobika commented on tests/test262-esnext-excludelist.xml
> -  <test id="built-ins/Object/hasOwn/descriptor.js"><reason></reason></test>
Please remove the comment around

2021-12-10 14:32 UTC, rerobika commented on jerry-core/ecma/operations/ecma-objects.c
> +extern inline ecma_value_t
This request is still valid

2021-12-15 09:27 UTC, rerobika commented on jerry-core/ecma/operations/ecma-objects.c
> +extern ecma_value_t
I think we can remove the extern keyword

2021-12-15 09:38 UTC, rerobika approved these changes

2021-12-15 10:37 UTC, ossy-szeged approved these changes

2021-12-15 10:38 UTC, merged