Outsource parser error messages
jerryscript-project/jerryscript pull request #4836
Opened 2021-11-25 14:01 UTC by repasics

Modify tools/gen-strings.py to generate error messages.

JerryScript-DCO-1.0-Signed-off-by: Csaba Repasi repasics@inf.u-szeged.hu

2021-11-25 14:04 UTC, rerobika requested changes

2021-11-25 14:04 UTC, rerobika commented on jerry-core/parser/js/parser-errors.h
> +#endif /* !PARSER_ERRORS_H */
#endif /* PARSER_ERRORS_H */

2021-11-25 14:04 UTC, rerobika commented on jerry-core/parser/js/parser-errors.h
> +#if JERRY_PARSER
This should be guarded with `JERRY_ERROR_MESSAGES`

2021-11-26 09:12 UTC, rerobika approved these changes
LGTM

2021-11-26 09:24 UTC, zherczeg approved these changes
LGTM

2021-11-26 09:26 UTC, merged