Implement ECMAScript 2022 class static block
jerryscript-project/jerryscript pull request #4841
Opened 2021-12-01 10:11 UTC by szilagyiadam

Co-authored-by: Martin Negyokru mnegyokru@inf.u-szeged.hu
JerryScript-DCO-1.0-Signed-off-by: Adam Szilagyi aszilagy@inf.u-szeged.hu

2021-12-06 09:41 UTC, rerobika requested changes

2021-12-06 09:41 UTC, rerobika commented on tests/jerry/es.next/class_static_block.js
> +assert(c === "second block")
no new line at the end of the file.

2021-12-06 09:41 UTC, rerobika commented on jerry-core/parser/js/js-parser-expr.c
> +      if (!lexer_check_next_character (context_p, LIT_CHAR_LEFT_PAREN) || is_static_block)
check is_static_block first

2021-12-06 09:41 UTC, rerobika commented on jerry-core/parser/js/js-lexer.c
> +  context_p->literal_count++;
Add check for maximum literal count first.

2021-12-13 08:58 UTC, rerobika approved these changes

2021-12-15 14:45 UTC, dbatyai approved these changes

2021-12-15 14:45 UTC, merged