Use external string when raising error
jerryscript-project/jerryscript pull request #4881
Opened 2021-12-09 12:11 UTC by repasics

JerryScript-DCO-1.0-Signed-off-by: Csaba Repasi repasics@inf.u-szeged.hu

2021-12-09 13:05 UTC, rerobika requested changes

2021-12-10 11:54 UTC, dbatyai requested changes

2021-12-10 11:54 UTC, dbatyai commented on jerry-core/ecma/operations/ecma-exceptions.c
> + *
The `char *` message argument should be replaced with `ecma_error_msg_t`, and this function should call `ecma_get_error_msg`. This guarantees that the string is a magic string and it exists statically, and then there's no reason for the note. Also the string size can then be retrieved, without the need for calling `lit_zt_utf8_string_size`.

2021-12-10 12:48 UTC, rerobika approved these changes
still LGTM

2021-12-10 17:14 UTC, dbatyai approved these changes

2021-12-10 17:15 UTC, merged