Fix redeclaration related eval corner cases
jerryscript-project/jerryscript pull request #4886
Opened 2021-12-09 14:10 UTC by szilagyiadam

- Fix cases where a function parameter binding is redeclared inside a parameter initializer eval
- Fix cases where a let- or function arguments binding is redeclared inside a function block because
  there is a declaration in a function parameter initializer eval
- Also remove the ECMA_PARSE_CHAIN_INDEX_SHIFT macro, added a debugger_eval_chain_index named field to the jerry context instead

JerryScript-DCO-1.0-Signed-off-by: Adam Szilagyi aszilagy@inf.u-szeged.hu

2021-12-09 14:24 UTC, rerobika requested changes

2021-12-09 14:24 UTC, rerobika commented on jerry-core/parser/js/js-scanner-util.c
> +#include <string.h>
is this really necessary?

2021-12-09 14:24 UTC, rerobika commented on jerry-core/parser/js/js-scanner-util.c
> +              //---------------
There are several comments here, please remove them.

2021-12-09 15:19 UTC, rerobika requested changes

2021-12-09 15:19 UTC, rerobika commented on jerry-core/parser/js/js-scanner-util.c
> +    if (ecma_compare_ecma_strings (arg_string, search_key_p))
save to local, free `search_key_p` only once

2021-12-09 15:19 UTC, rerobika commented on jerry-core/parser/js/js-scanner-util.c
> +  const ecma_compiled_code_t *bytecode_header_p = vm_context_p->shared_p->bytecode_header_p;
Query `JERRY_CONTEXT (vm_top_context_p)` only here

2021-12-10 08:59 UTC, szilagyiadam commented
Fixes #4896

2021-12-15 10:28 UTC, rerobika approved these changes

2021-12-15 11:45 UTC, ossy-szeged approved these changes

2021-12-15 11:45 UTC, merged