Fix class literal scan
jerryscript-project/jerryscript pull request #4906
Opened 2021-12-15 10:41 UTC by batizdaniel

This patch fixes #4892

JerryScript-DCO-1.0-Signed-off-by: Daniel Batiz daniel.batiz@h-lab.eu

2021-12-15 11:44 UTC, rerobika requested changes

2021-12-15 11:44 UTC, rerobika commented on jerry-core/parser/js/js-scanner-util.c
> +    if (stack_mode == SCAN_STACK_CLASS_STATEMENT || stack_mode == SCAN_STACK_CLASS_EXPRESSION)
This if can be removed

2021-12-15 12:14 UTC, rerobika approved these changes
LGTM

2021-12-22 13:50 UTC, dbatyai approved these changes

2021-12-22 13:50 UTC, merged