Fix runtime error: left shift
jerryscript-project/jerryscript pull request #4912
Opened 2021-12-22 09:39 UTC by batizdaniel

This patch fixes #4703

JerryScript-DCO-1.0-Signed-off-by: Daniel Batiz daniel.batiz@h-lab.eu

2021-12-22 12:19 UTC, dbatyai commented
I'm not a big fan of doing a clz call for every left shift operation, even if its handled by a builtin. It can have a significant performance overhead.

According to the C99 standard when the left value has an unsigned type the result will always be defined.

> If E1 has an unsigned type, the value of the result is E1 × 2^E2, reduced modulo
one more than the maximum value representable in the result type

If the goal is to avoid undefined behavior, we could just cast the left operand to unsigned, and the result would be the same for non-negative values.

For negative values it's not defined what the result should be, neither the C99, not the ecma standard provide anything specific. Looking at implementations however it seems that the same `E1 × 2^E2` rule is used for negative values as well.

So if the left value is negative, we could mask the low 31 bits, do an unsigned left shift to avoid undefined behavior, and if the result is non-zero, set the sign bit on the result.

IMO this approach would yield the same results as previously, avoids undefined behavior, and should also be much faster.

2021-12-22 13:10 UTC, batizdaniel commented
> 
I was not sure, what is the correct way to fix this. Your approach is much better. Fixed.

2021-12-22 13:32 UTC, dbatyai requested changes

2021-12-22 13:32 UTC, dbatyai commented on jerry-core/ecma/base/ecma-helpers-number.c
> +      (int32_t) ((uint32_t) right_integer << (__builtin_ctz ((unsigned int) left_integer))));
The shift in the condition after this will need a cast as well.

2021-12-22 13:53 UTC, dbatyai approved these changes

2021-12-23 10:33 UTC, rerobika approved these changes

2021-12-23 10:33 UTC, merged