Update build profile to es.next on esp8266
jerryscript-project/jerryscript pull request #4913
Opened 2021-12-22 12:36 UTC by mnegyokru

- fix amalgam build issue with es.next profile
  - update esp linker script according to: Table 4-1. in
    https://www.espressif.com/sites/default/files/documentation/2a-esp8266-sdk_getting_started_guide_en.pdf

JerryScript-DCO-1.0-Signed-off-by: Martin Negyokru negyokru@inf.u-szeged.hu

2021-12-22 13:20 UTC, dbatyai requested changes

2021-12-22 13:20 UTC, dbatyai commented on jerry-core/parser/js/js-parser.c
> +    source_name = context_p->options_p->source_name;
You could return directly, no need for the `source_name` variable.

2021-12-22 14:22 UTC, dbatyai approved these changes

2021-12-23 10:30 UTC, rerobika approved these changes

2021-12-23 10:30 UTC, merged