Remove ES_NEXT macro
jerryscript-project/jerryscript pull request #4915
Opened 2021-12-23 10:33 UTC by szilagyiadam

- remove all '#JERRY_ESNEXT' macro
- remove 5.1 build profile, update test runner accordingly (Note: all builtins are turn on by default)
- move tests from tests/jerry/esnext into tests/jerry, concatenate files with same names
- add skiplist to some snapshot tests that were supported only in 5.1
- fix doxygen issues that were hiden before (bc. of es.next macro)

Co-authored-by: Martin Negyokru negyokru@inf.u-szeged.hu
JerryScript-DCO-1.0-Signed-off-by: Adam Szilagyi aszilagy@inf.u-szeged.hu

2021-12-24 09:49 UTC, lygstate commented
neat, May separate the files rename to separate PR?

2022-01-03 08:26 UTC, rerobika requested changes

2022-01-03 08:26 UTC, rerobika commented on jerry-core/parser/js/common.c
> -#if JERRY_ESNEXT || JERRY_FUNCTION_TO_STRING
keep JERRY_FUNCTION_TO_STRING

2022-01-03 08:26 UTC, rerobika commented on jerry-core/parser/js/js-parser.c
> -#if JERRY_ESNEXT || JERRY_FUNCTION_TO_STRING
keep JERRY_FUNCTION_TO_STRING

2022-01-03 08:26 UTC, rerobika commented on jerry-core/parser/js/js-parser.c
> -#if JERRY_ESNEXT || JERRY_FUNCTION_TO_STRING
ditto

2022-01-03 08:26 UTC, rerobika commented on jerry-core/parser/js/js-parser.c
> -#if JERRY_ESNEXT || JERRY_FUNCTION_TO_STRING
keep JERRY_FUNCTION_TO_STRING

2022-01-03 08:39 UTC, lygstate commented on jerry-core/ecma/base/ecma-error-messages.inc.h
>  ECMA_ERROR_DEF (ECMA_ERR_ARRAYBUFFER_IS_DETACHED, "ArrayBuffer has been detached")
Does JERRY_ESNEXT implies ECMA_ERR_ARRAYBUFFER_IS_DETACHED?

2022-01-03 08:41 UTC, lygstate commented on jerry-core/ecma/base/ecma-error-messages.inc.h
> -#endif /* JERRY_BUILTIN_TYPEDARRAY \
Does this means JERRY_BUILTIN_TYPEDARRAY are always enabled by JERRY_ESNEXT

2022-01-03 08:42 UTC, lygstate commented on jerry-core/ecma/base/ecma-error-messages.inc.h
>  ECMA_ERROR_DEF (ECMA_ERR_ARGUMENT_THIS_NOT_DATE_OBJECT, "Argument 'this' is not a Date object")
Does this means JERRY_BUILTIN_DATE always enabled?

2022-01-03 08:42 UTC, lygstate commented on jerry-core/ecma/base/ecma-error-messages.inc.h
>  ECMA_ERROR_DEF (ECMA_ERR_INVALID_ARGUMENT_TYPE_IN_TOPRIMITIVE, "Invalid argument type in toPrimitive")
And this is different from 
```
ECMA_ERROR_DEF (ECMA_ERR_ARGUMENT_THIS_NOT_DATE_OBJECT, "Argument 'this' is not a Date object")
```

2022-01-31 11:06 UTC, rerobika approved these changes

2022-01-31 15:46 UTC, merged