Revise api reference documents after
jerryscript-project/jerryscript pull request #4972
Opened 2022-02-01 06:42 UTC by lygstate

https://github.com/jerryscript-project/jerryscript/pull/4915

JerryScript-DCO-1.0-Signed-off-by: Yonggang Luo luoyonggang@gmail.com

2022-02-01 09:36 UTC, rerobika requested changes

2022-02-01 09:36 UTC, rerobika commented on docs/02.API-REFERENCE.md
> +  - This API depends on a build option (`JERRY_BUILTIN_DATAVIEW`) and can be checked
This sentence seems unfinished to me. `and can be checked with [jerry_feature_enabled](#jerry_feature_enabled).`

2022-02-01 09:36 UTC, rerobika commented on docs/02.API-REFERENCE.md
> +These APIs all depends on a build option (`JERRY_BUILTIN_TYPEDARRAY`) and can be checked
depends -> depend

2022-02-01 09:36 UTC, rerobika commented on docs/02.API-REFERENCE.md
> +  - This API depends on a build option (`JERRY_BUILTIN_PROXY`) and can be checked
Ditto, same for all below.

2022-02-03 10:33 UTC, dbatyai approved these changes

2022-02-03 10:35 UTC, merged