Fixes nuttx target warning
jerryscript-project/jerryscript pull request #4984
Opened 2022-02-10 09:09 UTC by lygstate

```
jerry-main.c: In function 'str_to_uint':
jerry-main.c:89:12: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   89 |     *out_p = num_str_p;
make[4]: Leaving directory '/home/runner/work/jerryscript/jerryscript/targets/os/nuttx'
make[3]: Leaving directory '/home/runner/work/jerryscript/apps'
```

JerryScript-DCO-1.0-Signed-off-by: Yonggang Luo luoyonggang@gmail.com

2022-02-22 11:46 UTC, rtakacs commented
Good catch! I think, it's better to remove that parameter since `str_to_num` is used only once at [jerry-main.c:179](https://github.com/jerryscript-project/jerryscript/blob/master/targets/os/nuttx/jerry-main.c#L179) with NULL argument for `out_p`.

2022-03-02 12:34 UTC, rtakacs commented
LGTM (informal)

2022-03-02 12:38 UTC, robertsipka approved these changes
LGTM

2022-03-02 13:11 UTC, ossy-szeged approved these changes

2022-03-02 13:13 UTC, ossy-szeged requested changes
LGTM, but it would be great to have a formal commit message, we don"t put complete build logs to the commit messages.

2024-12-11 07:41 UTC, lygstate commented
Closed by accident, @ossy-szeged  updated and rebased

2024-12-17 09:15 UTC, robertsipka approved these changes
LGTM

2024-12-17 09:16 UTC, LaszloLango approved these changes

2024-12-17 09:17 UTC, merged