Fix the private field crash for the Array object.
jerryscript-project/jerryscript pull request #5139
Opened 2024-04-20 08:33 UTC by paintedveil5

Fix the private field crash in the Array object mentioned in 
https://github.com/jerryscript-project/jerryscript/issues/5138

2024-05-03 09:44 UTC, zherczeg commented
Good patch. Please add the testcase.

2024-05-03 14:30 UTC, paintedveil5 commented
> Good patch. Please add the testcase.

Added.

2024-05-04 04:39 UTC, zherczeg approved these changes
LGTM

2024-05-04 04:40 UTC, zherczeg commented
Please squash the commits and add DCO to the commit message.

2024-05-07 09:49 UTC, akosthekiss requested changes
The code seems OK, but the style of the test case addition is completely out of sync with the existing parts of the test case. Should be aligned.

2024-05-07 09:49 UTC, akosthekiss commented on tests/jerry/private_fields.js
> +class C3 extends Array{
style: no space between Array and {

2024-05-07 09:49 UTC, akosthekiss commented on tests/jerry/private_fields.js
> +  #a=1;
style: no spaces around =

2024-05-07 09:49 UTC, akosthekiss commented on tests/jerry/private_fields.js
> +  b(){
style: no space between ) and {

2024-05-07 09:49 UTC, akosthekiss commented on tests/jerry/private_fields.js
> +   }
style: unaligned }

2024-05-07 09:49 UTC, akosthekiss commented on tests/jerry/private_fields.js
> +assert(var17.b()==1);
style: no spaces around ==

2024-05-07 09:49 UTC, akosthekiss commented on tests/jerry/private_fields.js
> +class C4 extends Array{
style: no space between Array and {

2024-05-07 09:49 UTC, akosthekiss commented on tests/jerry/private_fields.js
> +  #a(){return 1};
style:
- no space between ) {
- return 1 should be on a separate line
- missing ; after return 1
- extra ; after }

2024-11-12 12:56 UTC, LaszloLango commented
@akosthekiss Please review the latest changes.

2024-11-25 07:54 UTC, robertsipka commented
I've updated the test cases and rebased to the master.
This PR fixes #5097 and #5100 and #5138 as well.

2024-11-25 08:04 UTC, LaszloLango commented
@robertsipka could you please add new regression tests with the issue numbers for all three?

2024-11-25 08:42 UTC, robertsipka commented
> @robertsipka could you please add new regression tests with the issue numbers for all three?

I've followed the author's original intention and amended the other two test cases to the test case which was originally included in the PR.

2024-11-25 12:02 UTC, LaszloLango approved these changes

2024-11-25 12:04 UTC, merged