Implement optional chaining
jerryscript-project/jerryscript pull request #5164
Opened 2024-11-14 12:17 UTC by gergocs

The work is based on PR #4843, only fixed some conflicts and cppcheck errors.

Co-authored-by: Robert Fancsik robert.fancsik@h-lab.eu
Signed-off-by: Gergo Csizi gergocs@inf.u-szeged.hu

2024-11-19 09:40 UTC, LaszloLango requested changes
I am a little bit worrying about the performance impact of this change. It would nice if we can make sure there is no regression in performance after this change.

2024-11-19 09:40 UTC, LaszloLango commented on jerry-core/vm/vm.c
> +          if (!ecma_is_value_null (left_value) && !ecma_is_value_undefined (left_value))
Please lets this be: `if (!(ecma_is_value_null (left_value) || ecma_is_value_undefined (left_value)))`

2024-11-19 09:40 UTC, LaszloLango commented on jerry-core/parser/js/js-parser-expr.c
> +static void
Lets make sure this is going to be an inline function:
`static inline void`

2024-11-19 09:40 UTC, LaszloLango commented on jerry-core/parser/js/js-parser-expr.c
> +        break;
Based on the comment above I don't understand why is this a `break` statement rather than a `continue`?

2024-11-20 09:51 UTC, robertsipka approved these changes
LGTM

2024-11-20 10:57 UTC, merged