Implement operations of atomics
jerryscript-project/jerryscript pull request #5166
Opened 2024-11-15 08:13 UTC by gergocs

The implementation is based on PR #4956, only resolved the conflicts.

JerryScript-DCO-1.0-Signed-off-by: Gergo Csizi gergocs@inf.u-szeged.hu

2024-11-20 16:57 UTC, LaszloLango requested changes
Could you please add more details into the commit message, what operations are implemented and what are still missing?

2024-11-21 22:00 UTC, ossy-szeged commented
Please add proper ifdef guard not to break non bigint build. See #5047 for details.

2024-11-25 13:00 UTC, zherczeg approved these changes
LGTM. Nice patch!

2024-11-25 13:12 UTC, LaszloLango requested changes

2024-11-26 07:59 UTC, gergocs commented on jerry-core/ecma/operations/ecma-arraybuffer-object.c
> +ecma_value_t
It is used in an other file so I don't think it should be static.

2024-11-26 09:05 UTC, LaszloLango approved these changes
LGTM

2024-11-26 09:56 UTC, merged