WIP - Update the API documentation
jerryscript-project/jerryscript pull request #5178
Opened 2024-11-25 16:07 UTC by LaszloLango

- Minor fixes, typos, version numbers, etc.
 - Followup fix after "Merge Promise Guard with ESNEXT #4725"

JerryScript-DCO-1.0-Signed-off-by: Laszlo Lango laszlo.lango@h-lab.eu

2024-12-05 12:26 UTC, robertsipka requested changes

2024-12-05 12:26 UTC, robertsipka commented on docs/02.API-REFERENCE.md
> +*Updated in version 3.0*: The following values are modified due to a typo in their names (exlcude/exclude):
The following values have been modified due to typos in their names.

2024-12-05 12:26 UTC, robertsipka commented on docs/02.API-REFERENCE.md
> +*Updated in version 2.0*: The exception handling and manipulation was modified and the old methods were replaced.
reckless nitpicking :)  "The exception handling and manipulation have been modified, and the old methods were replaced.

2024-12-05 12:26 UTC, robertsipka commented on docs/02.API-REFERENCE.md
> +- `realm` - release only those modules which realm value is equal to this argument.
Sorry for all the nitpicking, but you should use 'whose' instead of 'which' because it refers to possession.

2024-12-05 12:26 UTC, robertsipka commented on docs/02.API-REFERENCE.md
> +Checks wether the argument object has a native poitner set for the specified native type info.
There are two spelling mistakes here: "wether" -> "whether", "poitner" -> "pointer"

2024-12-11 05:32 UTC, zherczeg approved these changes
LGTM

2024-12-12 09:02 UTC, robertsipka approved these changes
LGTM

2024-12-12 19:39 UTC, merged